spring:
  application:
    name: mixi-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQP_URL:ENC(cKwWah5/eoPU3LqiZ42DKb93hn37V9BC118guCHwfFwcKkpdj69tJQCO0+h6kZpibt887ENhLI8=)}
    username: ${MYSQL_USERNAME:ENC(uKRMIxh1gV0iKm1iTmEx7A==)}
    password: ${MYSQL_PASSWORD:ENC(blcquWevQFa9Eif3xcgyoCU0P1F188dCsoD1eYbfwfY=)}
  redis:
    host: ${REDIS_HOST:ENC(fpt/v7Q3/B0Vdha9dT6q2Pcpg3+59qO+)}
    port: 6379
    database: 10
    password: ${REDIS_PASSWORD:ENC(vyGtzN2wnQlEdqsQmq1iVv6IvHW8Zifm8v48NSYNaq4=)}
email:
  myEmailAccount: ${ACCOUNT:ENC(3MXn8yuEtoudnkLj+3p7WkKhptSi8VcnYj9dAWmCL80=)}
  myEmailPassword: ${PASSWORD:ENC(45gxB10DLHgLm8EWI1C9guYfEeeLKxveTLwocYwccOQ=)}
env:
  ip: 127.0.0.1
  port: 9010
sa-token:
  token-name: token
  timeout: 259200
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true